import { ArrowRight, ArrowUpRight, Check } from 'lucide-react'
import { Link, Navigate, useParams } from 'react-router-dom'
import { industries, packages, projects, services, whatsappUrl } from '../../data/siteData'
import ContactSection from '../contact/ContactSection'
import { siteConfig } from '../../data/siteData'

const pageCopy = {
  work: ['Selected work', 'Ideas made visible.', 'A mix of product concepts and selected work. Client projects will only appear here when the details and outcomes are approved for publication.'],
  services: ['Services', 'The right shape for your next move.', 'Strategy, design and development can work as one connected process—whether you need a focused website or a complete operational product.'],
  pricing: ['Ways to work together', 'Scope first. A clear quote second.', 'Choose the closest starting point below. I’ll learn what your project actually needs, then send a scope-specific quote with milestones and no surprise line items.'],
  industries: ['Industries', 'Digital products shaped around real work.', 'Different sectors need different journeys, workflows and trust signals. The technology follows the people and the business—not the other way around.'],
  notFound: ['404 / Not found', 'This page has moved—or never existed.', 'The useful parts of the site are still close by. Head home, explore the work or start a conversation about your project.'],
}

function QuoteLink({ subject, children = 'Get a quote' }) {
  return <a className="button button-primary" href={whatsappUrl(subject)} target="_blank" rel="noreferrer">{children} <ArrowUpRight size={18} /></a>
}

export function ContentPage({ type }) {
  const [eyebrow, title, intro] = pageCopy[type]
  return (
    <div className="inner-page section-pad">
      <section className="inner-hero"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{intro}</p><QuoteLink subject={`${type} project`} /></section>
      {type === 'services' && <><div className="inner-list">{services.map(service => <Link key={service.slug} to={`/services/${service.slug}`}><span>{service.number}</span><h2>{service.title}</h2><p>{service.short}</p><ArrowRight /></Link>)}</div><section className="services-process" id="process"><div className="section-heading"><div><p className="section-number">Process</p><h2>A clear path from idea to <em>launch.</em></h2></div><p>Good work comes from good decisions. The process stays focused, collaborative and visible from the first conversation to handover.</p></div><div className="process-detail">{[['01','Discover','Goals, users and constraints'],['02','Design','Structure, interface and technical plan'],['03','Build','Milestones, staging and feedback'],['04','Launch','QA, deployment and steady improvement']].map(item => <div key={item[0]}><span>{item[0]}</span><h2>{item[1]}</h2><p>{item[2]}</p></div>)}</div></section></>}
      {type === 'pricing' && <div className="package-grid">{packages.map(item => <article className={`package-card ${item.featured ? 'featured' : ''}`} key={item.slug}><p className="package-label">{item.label}</p><h3>{item.name}</h3><p className="timeline">{item.timeline}</p><ul>{item.includes.map(x => <li key={x}><Check />{x}</li>)}</ul><QuoteLink subject={`${item.name} package: ${item.includes.join(', ')}`} /></article>)}</div>}
      {type === 'industries' && <div className="inner-list">{industries.map((industry, index) => <a key={industry} href={whatsappUrl(`a digital product for ${industry}`)} target="_blank" rel="noreferrer"><span>0{index + 1}</span><h2>{industry}</h2><p>Strategy, useful journeys and a reliable build shaped around your audience.</p><ArrowUpRight /></a>)}</div>}
      {type === 'work' && <div className="project-grid inner-projects">{projects.map(project => <article className="project-card" key={project.title}><div className="project-image"><img src={project.image} alt="Replaceable project concept visual" /><span>{project.type}</span></div><div className="project-info"><p>{project.services}</p><span>{project.year}</span><h3>{project.title}</h3><p className="project-description">{project.description}</p></div></article>)}</div>}
    </div>
  )
}

export function ServicePage() {
  const { slug } = useParams()
  const service = services.find(item => item.slug === slug)
  if (!service) return <Navigate to="/not-found" replace />
  const relevantPackages = service.slug === 'mobile-app-development' ? packages.slice(2, 3) : service.slug === 'business-systems' ? packages.slice(3) : packages.slice(0, 2)
  return <div className="inner-page section-pad">
    <section className="inner-hero"><p className="eyebrow">Service / {service.number}</p><h1>{service.title} that moves the business forward.</h1><p>{service.short}</p><Link className="button button-primary" to={`/contact?service=${service.slug}`}>Discuss this service <ArrowUpRight size={18} /></Link></section>
    <section className="service-detail-grid"><div><p className="section-number">What’s included</p><h2>A practical, outcome-led engagement.</h2></div><div>{service.details.map(item => <p key={item}><Check />{item}</p>)}<p><Check />Responsive, accessible implementation</p><p><Check />QA, deployment and handover</p></div><aside><small>Typical delivery</small><strong>{service.timeline}</strong><p>Exact scope and timings are confirmed after a short discovery conversation.</p></aside></section>
    <section className="service-story"><div><p className="section-number">Problems solved</p><h2>Less friction for your users and your team.</h2><p>This service is useful when the current experience is difficult to navigate, disconnected from business goals, costly to maintain or not ready for the next stage of growth.</p></div><div><p className="section-number">How it works</p>{['Align on goals, users and constraints', 'Shape the experience and technical direction', 'Build in reviewable milestones', 'Launch, document and improve'].map((item,index) => <p className="service-step" key={item}><span>0{index + 1}</span>{item}</p>)}</div></section>
    <section className="related-packages"><p className="section-number">Relevant ways to start</p><div className="package-grid">{relevantPackages.map(item => <article className="package-card" key={item.slug}><p className="package-label">{item.label}</p><h3>{item.name}</h3><p className="timeline">{item.timeline}</p><ul>{item.includes.map(x => <li key={x}><Check />{x}</li>)}</ul><QuoteLink subject={`${item.name} package (${item.includes.join(', ')})`}/></article>)}</div></section>
    <section className="service-links"><div><p className="section-number">Useful next steps</p><h2>See how the work comes together.</h2></div><nav><Link to="/work">Explore selected work →</Link><Link to="/services#process">Review the process →</Link><Link to="/pricing">Compare project scopes →</Link><Link to={`/contact?service=${service.slug}`}>Start an inquiry →</Link></nav></section>
    <section className="service-faq"><p className="section-number">Service FAQ</p>{[['Can this improve an existing product?', 'Yes. The first step is understanding what should be preserved, what is causing friction and whether focused improvements or a rebuild are more responsible.'], ['Will I own the finished work?', 'Project ownership transfers after final payment. Third-party services, licenses and subscriptions are documented separately.'], ['Can you work with an existing designer or team?', 'Yes. Responsibilities, handoff formats and review points are agreed at the start so collaboration stays clear.']].map(([q,a]) => <details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</section>
  </div>
}

export function ContactPage() {
  return <div className="contact-page"><section className="contact-hero section-pad"><p className="eyebrow">Start a project</p><h1>Tell me what you’re working on.</h1><p>A useful estimate starts with context. Share the essentials below and I’ll respond with questions, a recommended path or a focused discovery step.</p><div className="direct-contact-cards"><a href={`mailto:${siteConfig.email}`}><small>Email directly</small><strong>{siteConfig.email}</strong></a><a href={whatsappUrl()} target="_blank" rel="noreferrer"><small>Prefer a quick message?</small><strong>Chat on WhatsApp ↗</strong></a></div></section><ContactSection compact={false} /><section className="contact-guidance section-pad"><div><p className="section-number">A good fit</p><h2>Products with a clear business purpose.</h2><p>Ideal projects have an accountable decision-maker, a meaningful user problem and enough scope for strategy and quality implementation. A clear goal, audience, constraints and timing help me create the most useful estimate.</p></div><div className="next-steps"><span><b>01</b>Review request</span><span><b>02</b>Clarify scope</span><span><b>03</b>Proposal or discovery</span></div></section><section className="contact-faq section-pad"><p className="section-number">Contact FAQ</p>{[['When will I hear back?', siteConfig.responseWindow + '.'], ['Do you work internationally?', 'Yes. Remote collaboration uses clear milestones, written updates and planned overlap when needed.'], ['Can you sign an NDA?', 'Yes, when confidentiality is genuinely required. Private project details are never published without permission.'], ['How are budgets handled?', 'Your budget helps shape a realistic scope. Any commercial agreement is documented in a proposal before work begins.'], ['Who owns the project?', 'Ownership transfers after final payment, with third-party licenses and subscriptions documented separately.']].map(([q,a]) => <details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}<p className="privacy-note">Your information is used only to respond to the inquiry. Read the <Link to="/privacy">privacy notice</Link>.</p></section></div>
}

export function LegalPage({ type }) {
  const privacy = type === 'privacy'
  return <div className="legal-page section-pad"><p className="eyebrow">{privacy ? 'Privacy' : 'Terms'}</p><h1>{privacy ? 'Your information, handled with care.' : 'Clear expectations for using this site.'}</h1><h2>{privacy ? 'Information you share' : 'Website content'}</h2><p>{privacy ? 'If you contact me, I use the details you provide only to understand and respond to your inquiry. This website does not intentionally collect sensitive personal information.' : 'The content on this portfolio is provided for general information. Project scope, timelines and deliverables are only agreed through a written proposal.'}</p><h2>{privacy ? 'Third-party contact services' : 'Intellectual property'}</h2><p>{privacy ? 'Quote actions can open WhatsApp or your email client. Those services process data under their own privacy policies. Replace this draft with reviewed legal copy before launch.' : 'Unless stated otherwise, site design, text and code remain the property of Jigar Veera. Remote image placeholders belong to their respective owners.'}</p></div>
}
